# Generated by Django 5.0.2 on 2024-03-11 03:55

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the access type",
                        max_length=80,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "access type",
                "verbose_name_plural": "access types",
            },
        ),
        migrations.CreateModel(
            name="Complete_Portfolio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique identifier for the portfolio",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the portfolio"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education_Field",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique identifier for the Education",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "field_of_study",
                    models.CharField(
                        blank=True,
                        help_text="The field of study of the user",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "major",
                    models.CharField(
                        blank=True,
                        help_text="The major of the user",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "minor",
                    models.CharField(
                        blank=True,
                        help_text="The minor of the user",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique identifier for the portfolio item",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "icon",
                    models.URLField(
                        blank=True,
                        help_text="URL to the icon image",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the portfolio item", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the portfolio item"),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="URL to the portfolio item",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        blank=True,
                        help_text="The portfolio to which the item belongs",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="User.complete_portfolio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="The username of the user", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="The email of the user", max_length=254, unique=True
                    ),
                ),
                (
                    "roles",
                    models.CharField(
                        choices=[
                            ("User", "User"),
                            ("Organization", "Organization"),
                            ("Admin", "Admin"),
                        ],
                        default="User",
                        help_text="The role of the user",
                        max_length=100,
                    ),
                ),
                (
                    "profileImage",
                    models.URLField(
                        blank=True,
                        help_text="URL to the profile image",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "portfolioVisibility",
                    models.BooleanField(
                        default=True,
                        help_text="decides if the portfolio is visible to others",
                    ),
                ),
                (
                    "accessPermissions",
                    models.ManyToManyField(blank=True, to="auth.permission"),
                ),
                (
                    "accessType",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The access type of the user",
                        related_name="accessType",
                        to="User.accesstype",
                    ),
                ),
                (
                    "education",
                    models.OneToOneField(
                        blank=True,
                        help_text="The education of the user",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.education_field",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "portfolio",
                    models.OneToOneField(
                        blank=True,
                        help_text="The portfolio of the user",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.complete_portfolio",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.AddField(
            model_name="education_field",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="The user to whom the education belongs",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complete_portfolio",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="The user to whom the portfolio belongs",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
