# Generated by Django 5.0.2 on 2024-03-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstype",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="The permissions of the access type",
                to="auth.permission",
            ),
        ),
    ]
