# Generated by Django 5.0.2 on 2024-03-11 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_accesstype_permissions"),
    ]

    operations = [
        migrations.RemoveField(model_name="accesstype", name="permissions",),
    ]
