# Generated by Django 5.0.2 on 2024-03-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0004_remove_customuser_education_flair_roles_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="Flair_Roles",),
        migrations.RemoveField(model_name="flair_roles", name="role",),
        migrations.RemoveField(model_name="flair_roles", name="user",),
        migrations.AddField(
            model_name="flair_roles",
            name="role_name",
            field=models.CharField(
                help_text="The name of the role", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="flair_roles",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="flair_roles",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="User.flair_roles"
            ),
        ),
    ]
