# Generated by Django 5.0.2 on 2024-03-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0005_remove_customuser_flair_roles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flair_roles",
            name="id",
            field=models.AutoField(
                help_text="Unique identifier for the role",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
