# Generated by Django 5.0.2 on 2024-03-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0007_applink"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="roles",),
        migrations.AddField(
            model_name="customuser",
            name="education",
            field=models.TextField(
                blank=True, help_text="The education of the user", null=True
            ),
        ),
        migrations.AlterField(
            model_name="applink",
            name="google_calendar_link",
            field=models.URLField(
                blank=True, help_text="The link to the Google Calendar", null=True
            ),
        ),
        migrations.AlterField(
            model_name="applink",
            name="google_drive_link",
            field=models.URLField(
                blank=True, help_text="The link to the Google Drive", null=True
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Icon of the portfolio item",
                max_length=100,
                null=True,
            ),
        ),
    ]
