# Generated by Django 5.0.2 on 2024-04-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_remove_customuser_roles_customuser_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applink',
            name='event_form_link',
            field=models.URLField(blank=True, help_text='The link to the events form', null=True),
        ),
    ]
