# Generated by Django 5.0.2 on 2024-02-25 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0009_alter_customuser_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complete_portfolio",
            name="description",
            field=models.TextField(help_text="Description of the portfolio"),
        ),
        migrations.AlterField(
            model_name="complete_portfolio",
            name="id",
            field=models.AutoField(
                help_text="Unique identifier for the portfolio",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="complete_portfolio",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user to whom the portfolio belongs",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="portfolio",
            field=models.OneToOneField(
                blank=True,
                help_text="The portfolio of the user",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="User.complete_portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="portfolioVisibility",
            field=models.BooleanField(
                default=True, help_text="decides if the portfolio is visible to others"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profileImage",
            field=models.URLField(
                blank=True,
                help_text="URL to the profile image",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="description",
            field=models.TextField(help_text="Description of the portfolio item"),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="icon",
            field=models.URLField(
                blank=True, help_text="URL to the icon image", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="id",
            field=models.AutoField(
                help_text="Unique identifier for the portfolio item",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="URL to the portfolio item",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                help_text="The portfolio to which the item belongs",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="User.complete_portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="title",
            field=models.CharField(
                help_text="Title of the portfolio item", max_length=100
            ),
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_of_study",
                    models.CharField(
                        default="nothing",
                        help_text="The field of study of the user",
                        max_length=100,
                    ),
                ),
                (
                    "major",
                    models.CharField(
                        blank=True,
                        help_text="The major of the user",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "minor",
                    models.CharField(
                        blank=True,
                        help_text="The minor of the user",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user to whom the education belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
