# Generated by Django 5.0.2 on 2024-04-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_applink_event_form_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applink',
            name='event_form_link',
        ),
        migrations.AddField(
            model_name='applink',
            name='event_submission_form_link',
            field=models.URLField(blank=True, help_text='The link to the Event Submission form', null=True),
        ),
        migrations.AlterField(
            model_name='applink',
            name='feedback_form_link',
            field=models.URLField(blank=True, help_text='The link to the Contact Us / Feedback form', null=True),
        ),
        migrations.AlterField(
            model_name='applink',
            name='google_calendar_link',
            field=models.URLField(blank=True, help_text='The link to the embedded SIC Google Calendar', null=True),
        ),
        migrations.AlterField(
            model_name='applink',
            name='google_drive_link',
            field=models.URLField(blank=True, help_text='The link to the main Google Drive Folder', null=True),
        ),
    ]
