# Generated by Django 5.0.2 on 2024-04-07 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_remove_applink_event_form_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applink',
            name='google_drive_link',
        ),
    ]
