# Generated by Django 5.0.2 on 2024-02-25 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0011_alter_education_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complete_portfolio",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="The user to whom the portfolio belongs",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="field_of_study",
            field=models.CharField(
                blank=True,
                default="nothing",
                help_text="The field of study of the user",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="user",
            field=models.OneToOneField(
                help_text="The user to whom the education belongs",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
