# Generated by Django 5.0.2 on 2024-04-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_remove_applink_google_drive_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='applink',
            name='google_calendar_events_link',
            field=models.URLField(blank=True, help_text='The link to the Google Calendar Events', null=True),
        ),
        migrations.AlterField(
            model_name='applink',
            name='google_calendar_link',
            field=models.URLField(blank=True, help_text='The link to the embedded styled SIC Google Calendar', null=True),
        ),
    ]
