# Generated by Django 5.0.2 on 2024-02-25 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0012_alter_complete_portfolio_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolioitem",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                help_text="The portfolio to which the item belongs",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="User.complete_portfolio",
            ),
        ),
    ]
