# Generated by Django 5.0.2 on 2024-04-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_applink_google_calendar_events_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applink',
            name='spreadsheet_id',
            field=models.CharField(blank=True, help_text='The ID of the Google Spreadsheet containing the events', max_length=200, null=True),
        ),
    ]
