# Generated by Django 5.0.2 on 2024-04-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_applink_spreadsheet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profileImage',
            field=models.URLField(blank=True, help_text='URL to the profile image', max_length=150, null=True),
        ),
    ]
