# Generated by Django 5.0.2 on 2024-02-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_education_field_alter_customuser_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_field',
            name='field_of_study',
            field=models.CharField(blank=True, help_text='The field of study of the user', max_length=100, null=True),
        ),
    ]
