# Generated by Django 5.0.2 on 2024-02-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_alter_education_field_field_of_study'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstype',
            name='name',
            field=models.CharField(help_text='The name of the access type', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='accesstype',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='The permissions of the access type', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('User', 'User'), ('Organization', 'Organization'), ('Admin', 'Admin')], default='User', help_text='The role of the user', max_length=100),
        ),
    ]
