# Generated by Django 4.2.9 on 2024-02-22 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0003_customuser_role_portfolio_visibility_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("icon", models.URLField(blank=True, max_length=100, null=True)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("link", models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(model_name="portfolio", name="document",),
        migrations.RemoveField(model_name="portfolio", name="major",),
        migrations.RemoveField(model_name="portfolio", name="name",),
        migrations.RemoveField(model_name="portfolio", name="portfolio_link",),
        migrations.RemoveField(model_name="portfolio", name="user",),
        migrations.RemoveField(model_name="portfolio", name="visibility",),
        migrations.AddField(
            model_name="customuser",
            name="portfolio",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="User.portfolio",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="portfolioVisibility",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profileImage",
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="portfolioItem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="User.portfolioitem",
            ),
        ),
    ]
