# Generated by Django 4.2.9 on 2024-02-22 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0004_portfolioitem_remove_portfolio_document_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Portfolio", new_name="Complete_Portfolio",),
        migrations.RemoveField(model_name="complete_portfolio", name="portfolioItem",),
        migrations.AddField(
            model_name="complete_portfolio",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="User.complete_portfolio",
            ),
        ),
    ]
