# Generated by Django 4.2.9 on 2024-02-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0005_rename_portfolio_complete_portfolio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(model_name="customuser", name="role",),
        migrations.AddField(
            model_name="customuser",
            name="roles",
            field=models.ManyToManyField(related_name="users", to="User.role"),
        ),
    ]
