# Generated by Django 5.0.2 on 2024-02-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_role_remove_customuser_role_customuser_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('User', 'User'), ('Org', 'Org'), ('Admin', 'Admin')], default='User', max_length=100),
        ),
    ]
