# Generated by Django 5.0.2 on 2024-02-25 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0010_alter_complete_portfolio_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="user",
            field=models.OneToOneField(
                help_text="The user to whom the education belongs",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
