# Generated by Django 5.0.2 on 2024-02-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_customuser_accesspermissions_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='accessType',
            field=models.ManyToManyField(blank=True, help_text='The access type of the user', related_name='accessType', to='User.accesstype'),
        ),
    ]
