# Generated by Django 5.0.2 on 2024-02-26 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_alter_customuser_accesstype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.OneToOneField(blank=True, help_text='The education of the user', null=True, on_delete=django.db.models.deletion.CASCADE, to='User.education'),
        ),
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.AutoField(help_text='Unique identifier for the Education', primary_key=True, serialize=False),
        ),
    ]
