# Generated by Django 5.0.2 on 2024-02-26 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_remove_education_user_customuser_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education_Field',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for the Education', primary_key=True, serialize=False)),
                ('field_of_study', models.CharField(blank=True, default='nothing', help_text='The field of study of the user', max_length=100)),
                ('major', models.CharField(blank=True, help_text='The major of the user', max_length=100, null=True)),
                ('minor', models.CharField(blank=True, help_text='The minor of the user', max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, help_text='The user to whom the education belongs', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='education',
            field=models.OneToOneField(blank=True, help_text='The education of the user', null=True, on_delete=django.db.models.deletion.CASCADE, to='User.education_field'),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
