# Generated by Django 5.0.2 on 2024-03-11 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique identifier for the schedule",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 3, 11, 3, 55, 33, 49370, tzinfo=datetime.timezone.utc
                        ),
                        help_text="Start time of the schedule",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 3, 11, 3, 55, 33, 50124, tzinfo=datetime.timezone.utc
                        ),
                        help_text="End time of the schedule",
                    ),
                ),
                (
                    "visibility",
                    models.BooleanField(
                        default=True, help_text="Visibility of the schedule"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Title of the schedule",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resources",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique identifier for the asset",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the asset",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(help_text="Description of the asset")),
                (
                    "room_number",
                    models.CharField(
                        blank=True,
                        help_text="Room number of the asset",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("room", "Room"), ("equipment", "Equipment")],
                        help_text="Type of the asset",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
