# Generated by Django 5.0.2 on 2024-03-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique identifier for the schedule",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(help_text="Start time of the schedule"),
                ),
                (
                    "end_time",
                    models.DateTimeField(help_text="End time of the schedule"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resources",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique identifier for the asset",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the asset",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("description", models.TextField(help_text="Description of the asset")),
                (
                    "image",
                    models.FilePathField(
                        blank=True,
                        help_text="Path to the image of the asset",
                        null=True,
                        path="/resource/img",
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True,
                        help_text="Room number of the asset",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("room", "Room"),
                            ("equipment", "Equipment"),
                            ("other", "Other"),
                        ],
                        help_text="Type of the asset",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
