# Generated by Django 5.0.2 on 2024-03-11 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Booking", "0001_initial"),
        ("User", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                help_text="User that the schedule is for",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resources",
            name="access_type",
            field=models.ManyToManyField(
                help_text="The access type of the schedule", to="User.accesstype"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="resources",
            field=models.ForeignKey(
                help_text="Resource that the schedule is for",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="Booking.resources",
            ),
        ),
    ]
