# Generated by Django 5.0.2 on 2024-03-11 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0004_alter_booking_end_time_alter_booking_start_time"),
        ("User", "0003_remove_accesstype_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 11, 6, 17, 41, 479313, tzinfo=datetime.timezone.utc
                ),
                help_text="End time of the schedule",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 11, 6, 17, 41, 478878, tzinfo=datetime.timezone.utc
                ),
                help_text="Start time of the schedule",
            ),
        ),
        migrations.AlterField(
            model_name="resources",
            name="access_type",
            field=models.ManyToManyField(
                help_text="The access type for the resource", to="User.accesstype"
            ),
        ),
    ]
