# Generated by Django 5.0.2 on 2024-03-07 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_alter_booking_end_time_alter_booking_resources_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 4, 8, 29, 260083, tzinfo=datetime.timezone.utc), help_text='End time of the schedule'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 4, 8, 29, 260043, tzinfo=datetime.timezone.utc), help_text='Start time of the schedule'),
        ),
    ]
