# Generated by Django 5.0.2 on 2024-03-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0008_booking_title_booking_visibility_and_more'),
        ('Booking', '0009_alter_booking_end_time_alter_booking_start_time'),
    ]

    operations = [
    ]
