# Generated by Django 5.0.2 on 2024-03-07 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0010_merge_20240307_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 23, 24, 7, 910380, tzinfo=datetime.timezone.utc), help_text='End time of the schedule'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 23, 24, 7, 910359, tzinfo=datetime.timezone.utc), help_text='Start time of the schedule'),
        ),
    ]
