# Generated by Django 5.0.2 on 2024-03-16 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0012_alter_booking_end_time_alter_booking_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 16, 21, 3, 23, 910622, tzinfo=datetime.timezone.utc
                ),
                help_text="End time of the schedule",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 16, 21, 3, 23, 910385, tzinfo=datetime.timezone.utc
                ),
                help_text="Start time of the schedule",
            ),
        ),
        migrations.AlterField(
            model_name="resources",
            name="type",
            field=models.CharField(
                choices=[
                    ("room", "Room"),
                    ("equipment", "Equipment"),
                    ("maintenance", "Maintenance"),
                ],
                default="maintenance",
                help_text="Type of the asset",
                max_length=100,
            ),
        ),
    ]
