# Generated by Django 5.0.2 on 2024-03-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0016_alter_booking_end_time_alter_booking_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="end_time",
            field=models.DateTimeField(help_text="End time of the schedule"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_time",
            field=models.DateTimeField(help_text="Start time of the schedule"),
        ),
    ]
