# Generated by Django 4.2.9 on 2024-02-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_remove_customuser_roles_delete_role_customuser_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[(0, 'User'), (1, 'Organization'), (2, 'Admin')], default='User', max_length=100),
        ),
    ]
