# Generated by Django 4.2.9 on 2024-02-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_customuser_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('User', 'User'), ('Organization', 'Organization'), ('Admin', 'Admin')], default='User', max_length=100),
        ),
    ]
