name: Django CI

on:
  push:
    branches: [ "deployment" ]
  pull_request:
    branches: [ "deployment" ]

jobs:
  build:

    runs-on: 
      - self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Spin up venv
      run: |
        python -m venv env
        source env/bin/activate
    
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        sudo apt-get update
        sudo apt-get install sqlite3
        pip cache purge
        pip install -r requirements.txt --upgrade

    - name: Set up Google API credentials
      run: |
          echo "${{ secrets.SERVICE_CREDENTIALS }}" > service_credentials.json
        
    - name: Run Tests
      working-directory: backend
      run: |
        python3 manage.py test
